// <auto-generated />
namespace BTL_QLK.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class creat_table_Person : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(creat_table_Person));
        
        string IMigrationMetadata.Id
        {
            get { return "202110261137591_creat_table_Person"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
